services:
  livekit:
    image: livekit/livekit-server:v1.13.6
    container_name: sohbet-livekit
    command: ["--config", "/etc/livekit/livekit.yaml"]
    network_mode: host
    restart: always
    volumes:
      - ./livekit.yaml:/etc/livekit/livekit.yaml:ro
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  caddy:
    image: caddy:2-alpine
    container_name: sohbet-caddy
    network_mode: host
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy_data:/data
      - ./caddy_config:/config
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
